[project]
name = "trigger-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyserial>=3.5",
    "pyside2>=5.15.2.1",
    "pyyaml>=6.0.2",
]
